### ISSUE TITLE
Issue while trying to install Arseq on R version 3.6.1 - Mac 64bits

### ISSUE THREAD

**Issue by notreveh** [ajitjohnson/arseq#4]
* installing *source* package ‘arseq’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rJava/libs/rJava.so
  Reason: image not found
Execution halted
ERROR: lazy loading failed for package ‘arseq’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/arseq’
Error: Failed to install 'arseq' from GitHub:
  (converted from warning) installation of package ‘/var/folders/4b/5tnljr4d2gl9x2lh7_wr71sm0000gp/T//RtmpPvgRoU/file6bb51331452a/arseq_1.0.11.tar.gz’ had non-zero exit status

**Comment by ajitjohnson** [comment]
fixed it. Should work now :)

**Comment by notreveh** [comment]
Working perfectly. Thank you!
